language: node_js
node_js:
  - "6"
  - "5"
  - "4"
after_script:
  - node ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly
  - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
